csv, station.py 업로드
cobas67/Analysis_of_Subway_Data pull request #8
Opened 2024-12-02 23:52 UTC by Meojung1624

개인환경(vs코드) 에서 
pandas, matplotlib.pyplot 불러오기 오류로 실행확인 못했습니다 
추후 수정 필요 예상합니다

2024-12-03 02:17 UTC, cobas67 commented on station.py
추후 requirement 파일 추가 후 가상환경에서 실행하면 해결될꺼같습니다.

2024-12-04 01:28 UTC, llkll31 approved these changes
확인했습니다 ~

2024-12-04 06:10 UTC, llkll31 approved these changes
변경사항 확인했습니다

2024-12-04 06:26 UTC, llkll31 approved these changes

2024-12-04 06:33 UTC, cobas67 requested changes, later dismissed
리뷰확인

2024-12-04 06:35 UTC, cobas67 approved these changes

2024-12-04 06:38 UTC, llkll31 approved these changes
변경사항 검토했습니다

2024-12-04 06:40 UTC, cobas67 approved these changes

2024-12-04 06:41 UTC, cobas67 approved these changes

2024-12-04 06:41 UTC, cobas67 approved these changes

2024-12-04 06:45 UTC, llkll31 approved these changes
검토완료

2024-12-04 06:45 UTC, llkll31 commented on station.py
> +# 데이터 정제 완료 및 주요 함수 정의
확인했습니다

2024-12-04 06:50 UTC, merged